# Generated by Django 4.2 on 2024-11-06 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0001_initial'),
        ('metodo_pago', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id_factura', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_factura', models.DateField()),
                ('estado_factura', models.BooleanField(default=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cliente.cliente', verbose_name='Cliente')),
                ('metodo_pago', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='metodo_pago.metodopago', verbose_name='Método de Pago')),
            ],
            options={
                'verbose_name_plural': 'Facturas',
            },
        ),
    ]
