# Generated by Django 4.2 on 2024-11-06 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
        ('factura', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='factura',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Precio del producto en el momento de la compra', max_digits=10),
        ),
        migrations.AddField(
            model_name='factura',
            name='producto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='producto.producto'),
        ),
    ]
