# Generated by Django 4.2 on 2024-11-06 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id_vehiculo', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_vehiculo', models.CharField(max_length=100)),
                ('capacidad', models.DecimalField(decimal_places=2, help_text='Capacidad en unidades (ej. toneladas, m³)', max_digits=10)),
                ('consumo_combustible', models.DecimalField(decimal_places=2, help_text='Consumo de combustible en km/l', max_digits=10)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Vehículos',
            },
        ),
    ]
