# Generated by Django 4.2 on 2024-11-06 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('repartidor', '0001_initial'),
        ('factura', '0001_initial'),
        ('vehiculo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id_envio', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_envio', models.DateField()),
                ('costo_envio', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('direccion', models.CharField(max_length=255)),
                ('distancia_km', models.DecimalField(decimal_places=2, help_text='Distancia en kilómetros', max_digits=10)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='factura.factura', verbose_name='Factura')),
                ('repartidor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='repartidor.repartidor', verbose_name='Repartidor')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vehiculo.vehiculo', verbose_name='Vehículo')),
            ],
            options={
                'verbose_name_plural': 'Envios',
            },
        ),
    ]
